# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: Default

variables:
   imageName: 'POCMicroservices-Messagebroker-Web-docker'

 
steps:
 - task: Docker@2
   displayName: Build an image
   inputs:
     repository: $(imageName)
     command: build
     Dockerfile: Dockerfile

  # Build container image
 - task: Docker@1
   displayName: 'Build container image'
   inputs:
     imageName: '$(imageName):$(Build.BuildId)'
     useDefaultContext: false
     buildContext: '$(System.DefaultWorkingDirectory)/PublishedWebApp'

 - task: Docker@2
   inputs:
     containerRegistry: 'DockerHubServiceConnection'
     repository: 'pocmicroservices-messagebroker-web-docker'
     command: 'push'

